settings:
  title: 'Status Page'
  url: 'https://status.starsquare.co.uk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cmbuckley-co-uk
    name: cmbuckley.co.uk
    url: 'https://cmbuckley.co.uk/'
  - id: scripts-cmbuckley-co-uk
    name: scripts.cmbuckley.co.uk
    url: 'https://scripts.cmbuckley.co.uk/'
  - id: bux-re
    name: bux.re
    url: 'https://bux.re'
    expectStatus: 302
  - id: emilia-chris-wedding
    name: emilia-chris.wedding
    url: 'https://emilia-chris.wedding'
  - id: starsquare-co-uk
    name: starsquare.co.uk
    url: 'https://starsquare.co.uk'
  - id: vistaverde-network
    name: vistaverde.network
    url: 'https://vistaverde.network/cdn-cgi/trace'
  - id: icorrect-it
    name: icorrect.it
    url: 'https://icorrect.it'
  - id: emilia-buckley-name
    name: emilia.buckley.name
    url: 'https://emilia.buckley.name'
  - id: misterf-co-uk
    name: misterf.co.uk
    url: 'https://misterf.co.uk'
  - id: rfchildcareleeds-co-uk
    name: rfchildcareleeds.co.uk
    url: 'https://rfchildcareleeds.co.uk'
  - id: thesparesshop-co-uk
    name: thesparesshop.co.uk
    url: 'https://thesparesshop.co.uk'
  - id: yorkstudenthomes-com
    name: yorkstudenthomes.com
    url: 'https://yorkstudenthomes.com'
