settings:
  title: 'Status Page'
  url: 'https://status.starsquare.co.uk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Partially Degraded Service'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No Data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'No incidents'
  dayInHistogramNotOperational: ' incidents' # xx incidents recorded
  dayInHistogramNotOperationalOne: ' incident' # 1 incident recorded

monitors:
  - id: bux-re
    name: bux.re
    url: 'https://bux.re'
    expectStatus: 302
  - id: cmbuckley-co-uk
    name: cmbuckley.co.uk
    url: 'https://cmbuckley.co.uk/'
  - id: emilia-buckley-name
    name: emilia.buckley.name
    url: 'https://emilia.buckley.name'
  - id: emilia-chris-wedding
    name: emilia-chris-wedding.starsquare.co.uk
    url: 'https://emilia-chris-wedding.starsquare.co.uk'
  - id: icorrect-it
    name: icorrect.it
    url: 'https://icorrect.it'
  - id: misterf-co-uk
    name: misterf.co.uk
    url: 'https://misterf.co.uk'
  - id: pictures-scholesmafia-co-uk
    name: pictures.scholesmafia.co.uk
    url: 'https://pictures.scholesmafia.co.uk'
  - id: rfchildcareleeds-co-uk
    name: rfchildcareleeds.co.uk
    url: 'https://rfchildcareleeds.co.uk'
  - id: setcookie-net
    name: setcookie.net
    url: 'https://setcookie.net/'
  - id: scripts-cmbuckley-co-uk
    name: scripts.cmbuckley.co.uk
    url: 'https://scripts.cmbuckley.co.uk/'
  - id: starsquare-co-uk
    name: starsquare.co.uk
    url: 'https://starsquare.co.uk'
  - id: thesparesshop-co-uk
    name: thesparesshop.co.uk
    url: 'https://thesparesshop.co.uk'
  - id: vistaverde-network-home-assistant
    name: Home Assistant
    url: 'https://pi.vistaverde.network'
  - id: yorkstudenthomes-com
    name: yorkstudenthomes.com
    url: 'https://yorkstudenthomes.com'
