name = "cf-workers-status-page"
workers_dev = true
compatibility_date = "2021-10-05"
main = "index.js"

[[rules]]
type = "Data"
globs = ["**/*.yml", "**/*.yaml"]
fallthrough = true

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
