name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        packageManager: yarn
        preCommands: |
          yarn --silent wrangler kv:namespace list | jq -r 'map(select(.title | contains("KV_STATUS_PAGE")))[0].id'
          export KV_NAMESPACE_ID=$(yarn --silent wrangler kv:namespace list | jq -r 'map(select(.title | contains("KV_STATUS_PAGE")))[0].id')
          echo "KV: [$KV_NAMESPACE_ID]"
          [ -z "$KV_NAMESPACE_ID" ] && echo "Creating KV namespace" && yarn wrangler kv:namespace create KV_STATUS_PAGE
          export KV_NAMESPACE_ID=$(yarn --silent wrangler kv:namespace list | jq -r 'map(select(.title | contains("KV_STATUS_PAGE")))[0].id')
          echo "[env.production]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
          [ -z "$SECRET_SLACK_WEBHOOK_URL" ] && echo "Secret SECRET_SLACK_WEBHOOK_URL not set, creating dummy one..." && SECRET_SLACK_WEBHOOK_URL="default-gh-action-secret" || true
          [ -z "$SECRET_TELEGRAM_API_TOKEN" ] && echo "Secret SECRET_TELEGRAM_API_TOKEN not set, creating dummy one..." && SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret" || true
          [ -z "$SECRET_TELEGRAM_CHAT_ID" ] && echo "Secret SECRET_TELEGRAM_CHAT_ID not set, creating dummy one..." && SECRET_TELEGRAM_CHAT_ID="default-gh-action-secret" || true
          [ -z "$SECRET_DISCORD_WEBHOOK_URL" ] && echo "Secret SECRET_DISCORD_WEBHOOK_URL not set, creating dummy one..." && SECRET_DISCORD_WEBHOOK_URL="default-gh-action-secret" || true
        postCommands: |
          yarn kv-gc
        secrets: |
          SECRET_SLACK_WEBHOOK_URL
          SECRET_TELEGRAM_API_TOKEN
          SECRET_TELEGRAM_CHAT_ID
          SECRET_DISCORD_WEBHOOK_URL
          SECRET_HTTP_AUTH
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        SECRET_SLACK_WEBHOOK_URL: ${{secrets.SECRET_SLACK_WEBHOOK_URL}}
        SECRET_TELEGRAM_API_TOKEN: ${{secrets.SECRET_TELEGRAM_API_TOKEN}}
        SECRET_TELEGRAM_CHAT_ID: ${{secrets.SECRET_TELEGRAM_CHAT_ID}}
        SECRET_DISCORD_WEBHOOK_URL: ${{secrets.SECRET_DISCORD_WEBHOOK_URL}}
        SECRET_HTTP_AUTH: ${{secrets.SECRET_HTTP_AUTH}}
